- name: Update and upgrade apt packages
  apt:
    upgrade: dist
    update_cache: yes
  become: true

- name: Install useful packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - python3
    - python3-pip
    - zip
    - unzip
    - curl
    - wget
    - vim
    - htop
    - logrotate
  become: true

- name: Set timezone
  timezone:
    name: Europe/Paris
  become: true

- name: Set the locale
  locale_gen:
    name: en_GB.UTF-8
  become: true
