- name: Ensure Jenkins APT key is installed
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins.io.key
    state: present
  become: true

- name: Ensure Jenkins APT repository is configured
  apt_repository:
    repo: deb https://pkg.jenkins.io/debian-stable binary/
    state: present
  become: true

- name: Ensure Jenkins is installed
  apt:
    name: jenkins
    update_cache: yes
  become: true

- name: Disable Jenkins setup wizard
  lineinfile:
    path: /etc/default/jenkins
    regexp: '^JAVA_ARGS='
    line: 'JAVA_ARGS="-Djenkins.install.runSetupWizard=false"'
  become: true

- name: Add the environment variable to Jenkins service to point to the configuration as code
  lineinfile:
    path: /usr/lib/systemd/system/jenkins.service
    regexp: '^Environment='
    line: 'Environment="JAVA_OPTS=-Dcasc.jenkins.config=/var/jenkins_home/casc_configs/jenkins.yaml"'
  become: true

- name: Ensure Jenkins is running
  service:
    name: jenkins
    state: started
    enabled: yes
  become: true

- name: Create all needed folders (/var/whanos, /var/jenkins_home/casc_configs, /usr/share/jenkins/ref/init.groovy.d)
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - {path: "/var/whanos", owner: "jenkins", group: "jenkins", mode: "0755"}
    - {path: "/var/jenkins_home/casc_configs", owner: "jenkins", group: "jenkins", mode: "0755"}
    - {path: "/usr/share/jenkins/ref/init.groovy.d", owner: "jenkins", group: "jenkins", mode: "0755"}
  become: true

- name: Put files in place
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - {src: "../../../../jenkins/plugins.txt", dest: "/var/whanos/plugins.txt", owner: "jenkins", group: "jenkins", mode: "0644"}
    - {src: "../../../../jenkins/jenkins.yml", dest: "/var/jenkins_home/casc_configs/jenkins.yaml", owner: "jenkins", group: "jenkins", mode: "0644"}
    - {src: "../../../../jenkins/job_dsl.groovy", dest: "/usr/share/jenkins/ref/init.groovy.d/job_dsl.groovy", owner: "jenkins", group: "jenkins", mode: "0644"}
    - {src: "../../../../jenkins/docker-deploy.sh", dest: "/var/whanos/docker-deploy.sh", owner: "jenkins", group: "jenkins", mode: "0755"}
  become: true

- name: Install Jenkins plugins
  command: "java -jar jenkins-cli.jar -s http://localhost:8080/ install-plugin `cat /var/whanos/plugins.txt | tr '\n' ' '`"
  become: true

- name: Restart Jenkins
  command: "systemctl restart jenkins"
  become: true
