FROM gcc:13.2 as builder

SHELL ["/bin/bash", "-c"]

ONBUILD WORKDIR /app
ONBUILD COPY . /app
ONBUILD RUN git clone https://github.com/catseye/Befunge-93.git
ONBUILD WORKDIR /app/Befunge-93
ONBUILD RUN make
ONBUILD WORKDIR /app
ONBUILD RUN cp /app/Befunge-93/bin/bef .
ONBUILD RUN rm -rf /app/Befunge-93/
ONBUILD CMD ["./bef" , "app/main.bf"]
