FROM maven:3.9.6-eclipse-temurin-21 as builder

SHELL ["/bin/bash", "-c"]
COPY . /app
WORKDIR /app
RUN mvn compile -f app/pom.xml
RUN mvn package -f app/pom.xml
RUN cp app/target/app.jar .
RUN rm -rf app/


FROM eclipse-temurin:21
SHELL ["/bin/bash", "-c"]
COPY --from=builder /app /app
WORKDIR /app
CMD ["java", "-jar", "app.jar"]
