FROM maven:3.9.6-eclipse-temurin-21 as builder

ONBUILD SHELL ["/bin/bash", "-c"]
ONBUILD COPY . /app
ONBUILD WORKDIR /app
ONBUILD RUN mvn compile -f app/pom.xml
ONBUILD RUN mvn package -f app/pom.xml
ONBUILD RUN cp app/target/app.jar .
ONBUILD RUN rm -rf app/
ONBUILD CMD ["java", "-jar", "app.jar"]
