- name: Install Docker
  apt:
    name: docker.io
    state: present
  become: true

- name: Ensure Docker is running
  become: true
  service:
    name: docker
    state: started
    enabled: yes
    daemon_reload: yes

- name: Copy the Dockerfile images in the registry to /opt/registry
  copy:
    src: "../../../../images/"
    dest: "/opt/registry/"
    directory_mode: yes
    group: docker
  become: true

- name: Set permission so everyone can read the Dockerfile images
  command: "chmod -R 0755 /opt/registry"
  become: true

- name: Create needed /opt/registry/docker folder
  file:
    path: "/opt/registry/docker"
    state: directory
    owner: root
    group: docker
    mode: 0755
  become: true

- name: Build the Docker images (base)
  command: "docker build -t {{ item.tag }} -f {{ item.path }} /opt/registry"
  with_items:
    - { tag: "{{ registry }}/whanos-befunge", path: "/opt/registry/befunge/Dockerfile.base" }
    - { tag: "{{ registry }}/whanos-javascript", path: "/opt/registry/javascript/Dockerfile.base" }
    - { tag: "{{ registry }}/whanos-python", path: "/opt/registry/python/Dockerfile.base" }
    - { tag: "{{ registry }}/whanos-java", path: "/opt/registry/java/Dockerfile.base" }
    - { tag: "{{ registry }}/whanos-c", path: "/opt/registry/c/Dockerfile.base" }
  become: true

- name: Login to our Docker registry
  command: "docker login {{ registry }} -u {{ registry_user }} -p {{ registry_password }}"
  become: true

- name: Push the Docker images to our Docker registry
  command: "docker push {{ registry }}/{{ item.tag }}"
  with_items:
    - { tag: "whanos-befunge" }
    - { tag: "whanos-javascript" }
    - { tag: "whanos-python" }
    - { tag: "whanos-java" }
    - { tag: "whanos-c" }
  become: true
