- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  become: true

- name: Add the repository to Apt sources
  command: "echo 'deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable' | tee /etc/apt/sources.list.d/docker.list"
  become: true

- name: Install Docker
  apt:
    name: docker.io
    state: present
  become: true

- name: Ensure Docker is running
  become: true
  service:
    name: docker
    state: started
    enabled: yes
    daemon_reload: yes

- name: Start a REGISTRY container
  docker_container:
    name: registry
    image: registry:2
    state: started
    restart_policy: always
    ports:
      - "5000:5000"
    volumes:
      - /opt/registry:/var/lib/registry
    env:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
  become: true

- name: Copy the Dockerfile images in the registry to /opt/registry
  copy:
    src: "../../../../images/"
    dest: "/opt/registry/"
    directory_mode: yes
    mode: 0755
  become: true

- name: Build the Docker images (base)
  command: "docker build -t {{ item.tag }} -f {{ item.path }} /opt/registry"
  with_items:
    - { tag: "befunge-base", path: "/opt/registry/befunge/Dockerfile.base" }
    - { tag: "javascript-base", path: "/opt/registry/javascript/Dockerfile.base" }
    - { tag: "python-base", path: "/opt/registry/python/Dockerfile.base" }
    - { tag: "java-base", path: "/opt/registry/java/Dockerfile.base" }
    - { tag: "c-base", path: "/opt/registry/c/Dockerfile.base" }
  become: true
