services:
  jenkins:
    build:
      context: "."
    ports:
      - 8080:8080
    volumes:
      - ./my_whanos.yml:/var/jenkins_conf
      - jenkins_home:/var/jenkins_home
    env_file:
      - .env

  registry:
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - registry_data:/var/lib/registry
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry

volumes:
  jenkins_home:
  registry_data:
