- name: Install NGINX
  apt:
    name: nginx
    state: present
  become: true

- name: Disable NGINX Default Virtual Host
  command:
    cmd: "unlink /etc/nginx/sites-enabled/default"
  become: true

- name: Copy NGINX Configuration
  copy:
    src: "nginx.conf"
    dest: "/etc/nginx/conf.d/default.conf"
  become: true

- name: Restart NGINX
  service:
    name: nginx
    state: restarted
  become: true
