- name: Base
  hosts: all
  roles:
    - base
  tags: base

- name: Docker Registry
  hosts: jenkins
  roles:
    - registry
  tags: docker-registry

- name: Kubernetes
  hosts: jenkins
  roles:
    - k8s
  tags: k8s

- name: Jenkins
  hosts: jenkins
  roles:
    - jenkins
  tags: jenkins

- name: NGINX Reverse Proxy
  hosts: jenkins
  roles:
    - nginx
  tags: nginx
