- name: Base
  hosts: all
  roles:
    - base
  tags: base

- name: Docker Registry
  hosts: jenkins
  roles:
    - registry
  tags: docker-registry

- name: Jenkins
  hosts: jenkins
  roles:
    - java
    - jenkins
  tags: jenkins
