- name: Install useful packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
  become: true

- name: Get Helm gpg key
  apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present
  become: true

- name: Add Helm repository
  apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present
  become: true

- name: Install Helm
  apt:
    name: helm
    state: present
  become: true

- name: Copy the helm chart to the remote host
  copy:
    src: helm-chart
    dest: /helm-chart
  become: true
