FROM python:3.12-alpine

RUN apk add --no-cache bash
SHELL ["/bin/bash", "-c"]
ONBUILD COPY . /app
ONBUILD WORKDIR /app
ONBUILD RUN pip install -r requirements.txt
ONBUILD CMD ["python", "-m", "app"]
